springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v3/api-docs

app:
  commercetools:
    projectKey: training_riya_goyal
    clientId: i28jCGsgm-Otbufh81JtjBEj
    clientSecret: kdcvoS9BsREsnyTbTBD-z-Wuu84d9kcd

server:
  port: 8080

